/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokeTec.gui;

import java.awt.BasicStroke;
import java.awt.Canvas;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JFrame;
import static javax.swing.JOptionPane.showMessageDialog;
import pokeTec.estructuras.Arista;
import pokeTec.estructuras.DoubleLinkedList;
import pokeTec.estructuras.DoubleLinkedNode;

import pokeTec.logica.GestionPokePlace;
import pokeTec.logica.GestionPokemon;
import pokeTec.logica.ModeladorTablas;
import pokeTec.logica.PokePlace;
import pokeTec.logica.Pokemon;

/**
 *
 * @author Mata
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private GestionPokePlace gestorPlace;
    private GestionPokemon gestorPokemo;

    public GestionPokePlace getGestorPlace() {
        return gestorPlace;
    }

    public void setGestorPlace(GestionPokePlace gestorPlace) {
        this.gestorPlace = gestorPlace;
    }

    public GestionPokemon getGestorPokemo() {
        return gestorPokemo;
    }

    public void setGestorPokemo(GestionPokemon gestorPokemo) {
        this.gestorPokemo = gestorPokemo;
    }

    public Principal() {
        this.gestorPlace = new GestionPokePlace();
        this.gestorPokemo = new GestionPokemon();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        comboTipo = new javax.swing.JComboBox<>();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        txtX = new javax.swing.JTextField();
        txtY = new javax.swing.JTextField();
        label5 = new java.awt.Label();
        txtId = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVertices = new javax.swing.JTable();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        txtIDPartida = new javax.swing.JTextField();
        txtIDLlegada = new javax.swing.JTextField();
        btnAgregarRuta = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableAristas = new javax.swing.JTable();
        btnGrafoI = new javax.swing.JButton();
        btnDijkstra = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        editorTexto = new javax.swing.JTextPane();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        label18 = new java.awt.Label();
        label19 = new java.awt.Label();
        txtNombre = new javax.swing.JTextField();
        txtPreEvolucion = new javax.swing.JTextField();
        txtEspecie = new javax.swing.JTextField();
        txtPosibleEvo = new javax.swing.JTextField();
        txtPadre = new javax.swing.JTextField();
        txtHijo = new javax.swing.JTextField();
        txtAtaque = new javax.swing.JTextField();
        txtDefensa = new javax.swing.JTextField();
        txtAtaqueesp = new javax.swing.JTextField();
        txtDefEsp = new javax.swing.JTextField();
        btnPokemon = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablePokemones = new javax.swing.JTable();
        btnGrafoPokemon = new javax.swing.JButton();
        btnRelacionar = new javax.swing.JButton();
        txtgrafoH = new javax.swing.JTextField();
        label20 = new java.awt.Label();
        label21 = new java.awt.Label();
        txtGrafoP = new javax.swing.JTextField();
        label22 = new java.awt.Label();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableRelacion = new javax.swing.JTable();
        btnVerGrafo = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label1.setText("Create Route");

        label2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label2.setText("Type: ");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Punto de Captura", "Hospital Pokemon", "Poke Restaurante", "Tienda Pokemon", "Gimnasio Pokemon" }));

        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setText("Name");

        label4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label4.setText("Y:");

        label5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label5.setText("ID:");

        btnIngresar.setText("Enter");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        tableVertices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tipo", "X", "Y", "ID", "ID Dijkstra"
            }
        ));
        jScrollPane1.setViewportView(tableVertices);

        label6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label6.setText("Add PokePlace");

        label7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label7.setText("Starting point: ");

        label8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label8.setText("Arrival point: ");

        btnAgregarRuta.setText("Add Route");
        btnAgregarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRutaActionPerformed(evt);
            }
        });

        tableAristas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Camino", "ID Partida", "ID Llegada", "Distancia"
            }
        ));
        jScrollPane2.setViewportView(tableAristas);

        btnGrafoI.setText("Inicilizate Graph");
        btnGrafoI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrafoIActionPerformed(evt);
            }
        });

        btnDijkstra.setText("Dijkstra");
        btnDijkstra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDijkstraActionPerformed(evt);
            }
        });

        editorTexto.setEditable(false);
        jScrollPane3.setViewportView(editorTexto);

        label9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label9.setText("Create Pokemon");

        label10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label10.setText("X: ");

        label11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label11.setText("Kind");

        label12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label12.setText("Preevolution");

        label13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label13.setText("Father");

        label14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label14.setText("Son");

        label15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label15.setText("PosibleEvolution");

        label16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label16.setText("Attack");

        label17.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label17.setText("Defense");

        label18.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label18.setText("Special Attack");

        label19.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label19.setText("Special Defense");

        btnPokemon.setText("Add Pokemon");
        btnPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokemonActionPerformed(evt);
            }
        });

        tablePokemones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Especie", "PreEvolucion", "PosibleEvo", "Padre", "Hijo", "Ataque", "Defensa", "Ataque Especial", "DefensaEspecial"
            }
        ));
        jScrollPane5.setViewportView(tablePokemones);

        btnGrafoPokemon.setText("Inicializate Graph");
        btnGrafoPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrafoPokemonActionPerformed(evt);
            }
        });

        btnRelacionar.setText("Relate");
        btnRelacionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelacionarActionPerformed(evt);
            }
        });

        label20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label20.setText("Son");

        label21.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label21.setText("Father");

        label22.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label22.setText("Relate");

        tableRelacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Relacion", "ID Padre", "ID Hijo"
            }
        ));
        jScrollPane6.setViewportView(tableRelacion);

        btnVerGrafo.setText("See Graph");
        btnVerGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerGrafoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtY))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtX))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(654, 654, 654)
                        .addComponent(btnVerGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDijkstra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregarRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIDLlegada)
                            .addComponent(txtIDPartida)
                            .addComponent(btnGrafoI, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnRelacionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtgrafoH)
                                    .addComponent(txtGrafoP)
                                    .addComponent(btnGrafoPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(95, 95, 95)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPreEvolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtHijo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDefensa, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(200, 200, 200)
                                        .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(175, 175, 175)
                                        .addComponent(btnPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(292, 292, 292)))
                            .addComponent(txtDefEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPosibleEvo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAtaqueesp, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtIDPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarRuta)
                        .addGap(18, 18, 18)
                        .addComponent(btnGrafoI)
                        .addGap(18, 18, 18)
                        .addComponent(btnDijkstra)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDefEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(20, 20, 20)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txtHijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txtEspecie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addComponent(txtAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtPreEvolucion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtDefensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAtaqueesp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtPosibleEvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addComponent(btnIngresar))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addComponent(btnVerGrafo)
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtGrafoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtgrafoH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnRelacionar)
                                .addGap(18, 18, 18)
                                .addComponent(btnGrafoPokemon))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)))))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed

        try {
            String tipo = this.comboTipo.getSelectedItem().toString();
            int x = Integer.parseInt(this.txtX.getText());
            int y = Integer.parseInt(this.txtY.getText());
            String id = this.txtId.getText();
            PokePlace place = new PokePlace(tipo, x, y, id);
            this.gestorPlace.nuevoVertice(place);

            actualizarTablaPlaces();
        } catch (Exception e) {
            showMessageDialog(null, "ERROR");
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnAgregarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRutaActionPerformed
        try {
            PokePlace partida = this.gestorPlace.buscarPlaceId(this.txtIDPartida.getText());
            PokePlace llegada = this.gestorPlace.buscarPlaceId(this.txtIDLlegada.getText());
            this.gestorPlace.nuevaArista(partida, llegada);
            showMessageDialog(null, "Se agrego de: " + this.gestorPlace.buscarPlaceId(this.txtIDPartida.getText()).getId()
                    + " a " + this.gestorPlace.buscarPlaceId(this.txtIDLlegada.getText()).getId());
        } catch (Exception e) {
            showMessageDialog(null, "ERROR");
        }

    }//GEN-LAST:event_btnAgregarRutaActionPerformed

    private void btnGrafoIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrafoIActionPerformed
        try {
            this.gestorPlace.inicializarGrafo();
            actualizarTablaRutas();
        } catch (Exception e) {
            showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btnGrafoIActionPerformed

    private void btnDijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDijkstraActionPerformed
        try {
            int partida = Integer.parseInt(this.txtIDPartida.getText());
            int llegada = Integer.parseInt(this.txtIDLlegada.getText());
            this.editorTexto.setText(this.gestorPlace.dijkstra(partida, llegada));
        } catch (Exception e) {
            showMessageDialog(null, "ERROR");
        }


    }//GEN-LAST:event_btnDijkstraActionPerformed

    private void btnPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokemonActionPerformed
        try {

            String nombre = this.txtNombre.getText();
            String especie = this.txtEspecie.getText();
            String preevolucion = this.txtPreEvolucion.getText();
            String posibleEvo = this.txtPosibleEvo.getText();
            String padre = this.txtPadre.getText();
            String hijo = this.txtHijo.getText();
            int ataque = Integer.parseInt(this.txtAtaque.getText());
            int defensa = Integer.parseInt(this.txtDefensa.getText());
            int ataqueEsp = Integer.parseInt(this.txtAtaqueesp.getText());
            int defensaEsp = Integer.parseInt(this.txtDefEsp.getText());
            Pokemon pokemon = new Pokemon(especie, nombre, preevolucion, posibleEvo, padre, hijo, ataque, defensa, ataqueEsp, defensaEsp);
            this.gestorPokemo.nuevoVertice(pokemon);
            actualizarTablaPokemones();
        } catch (Exception e) {
            showMessageDialog(null, "ERROR");
        }

    }//GEN-LAST:event_btnPokemonActionPerformed

    private void btnGrafoPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrafoPokemonActionPerformed
        this.gestorPokemo.inicializarGrafo();
        actualizarTablaR();
    }//GEN-LAST:event_btnGrafoPokemonActionPerformed

    private void btnRelacionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelacionarActionPerformed

        try {
            Pokemon padre = this.gestorPokemo.buscarNombre(this.txtGrafoP.getText());
            Pokemon hijo = this.gestorPokemo.buscarNombre(this.txtgrafoH.getText());
            this.gestorPokemo.nuevaArista(padre, hijo);
            showMessageDialog(null, "Se relaciona: " + this.gestorPokemo.buscarNombre(this.txtGrafoP.getText()).getNombre()
                    + "a " + this.gestorPokemo.buscarNombre(this.txtgrafoH.getText()).getNombre());
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnRelacionarActionPerformed

    private void btnVerGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerGrafoActionPerformed
        // TODO add your handling code here:
        canvas c = new canvas();
    }//GEN-LAST:event_btnVerGrafoActionPerformed
    public void actualizarTablaPlaces() {

        ModeladorTablas.vaciarTabla(this.tableVertices);
        Object[] filaNueva;
        DoubleLinkedNode<PokePlace> temp = this.gestorPlace.getListaPlaces().getHead();
        for (int i = 0; i < this.gestorPlace.getListaPlaces().getSize(); i++) {
            filaNueva = new Object[]{temp.getElement().getTipo(),
                temp.getElement().getX(),
                temp.getElement().getY(),
                temp.getElement().getId(),
                temp.getElement().getIdLista()};
            ModeladorTablas.nuevaFila(this.tableVertices, filaNueva);
            temp = temp.getNext();
        }
    }

    public void actualizarTablaRutas() {

        ModeladorTablas.vaciarTabla(this.tableAristas);
        Object[] filaNueva;

        for (int i = 0; i < this.gestorPlace.getGrafo().getAristas().size(); i++) {
            Arista temp = this.gestorPlace.getGrafo().getAristas().get(i);
            filaNueva = new Object[]{temp.getId_arista(),
                temp.getPuntoPartida().getId(),
                temp.getPuntoLlegada().getId(),
                temp.getLongitud()};
            ModeladorTablas.nuevaFila(this.tableAristas, filaNueva);

        }
    }

    public void actualizarTablaPokemones() {

        ModeladorTablas.vaciarTabla(this.tablePokemones);
        Object[] filaNueva;
        DoubleLinkedNode<Pokemon> temp = this.gestorPokemo.getListaPoke().getHead();
        for (int i = 0; i < this.gestorPokemo.getListaPoke().getSize(); i++) {
            filaNueva = new Object[]{temp.getElement().getNombre(),
                temp.getElement().getEspecie(),
                temp.getElement().getPreevolucion(),
                temp.getElement().getPosibleEvolucion(),
                temp.getElement().getPadre(),
                temp.getElement().getHijos(),
                temp.getElement().getAtaque(),
                temp.getElement().getDefensa(),
                temp.getElement().getAtaqueEsp(),
                temp.getElement().getDefensaEsp()};
            ModeladorTablas.nuevaFila(this.tablePokemones, filaNueva);
            temp = temp.getNext();
        }
    }

    public void actualizarTablaR() {

        ModeladorTablas.vaciarTabla(this.tableRelacion);
        Object[] filaNueva;

        for (int i = 0; i < this.gestorPokemo.getGrafo().getAristas().size(); i++) {
            Arista temp = this.gestorPokemo.getGrafo().getAristas().get(i);
            filaNueva = new Object[]{temp.getId_arista(),
                temp.getPuntoPartida().getId(),
                temp.getPuntoLlegada().getId()};
            ModeladorTablas.nuevaFila(this.tableRelacion, filaNueva);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarRuta;
    private javax.swing.JButton btnDijkstra;
    private javax.swing.JButton btnGrafoI;
    private javax.swing.JButton btnGrafoPokemon;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnPokemon;
    private javax.swing.JButton btnRelacionar;
    private javax.swing.JButton btnVerGrafo;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JTextPane editorTexto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label2;
    private java.awt.Label label20;
    private java.awt.Label label21;
    private java.awt.Label label22;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JTable tableAristas;
    private javax.swing.JTable tablePokemones;
    private javax.swing.JTable tableRelacion;
    private javax.swing.JTable tableVertices;
    private javax.swing.JTextField txtAtaque;
    private javax.swing.JTextField txtAtaqueesp;
    private javax.swing.JTextField txtDefEsp;
    private javax.swing.JTextField txtDefensa;
    private javax.swing.JTextField txtEspecie;
    private javax.swing.JTextField txtGrafoP;
    private javax.swing.JTextField txtHijo;
    private javax.swing.JTextField txtIDLlegada;
    private javax.swing.JTextField txtIDPartida;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPadre;
    private javax.swing.JTextField txtPosibleEvo;
    private javax.swing.JTextField txtPreEvolucion;
    private javax.swing.JTextField txtX;
    private javax.swing.JTextField txtY;
    private javax.swing.JTextField txtgrafoH;
    // End of variables declaration//GEN-END:variables
 //para visualizar el grafo
    class canvas extends JFrame {

        // create a canvas 
        Canvas c;

        // constuctor 
        canvas() {
            super("canvas");

            // create a empty canvas 
            c = new Canvas() {
                public void paint(Graphics g) {
                    super.paint(g);
                    Graphics2D circulo = (Graphics2D) g;
                    circulo.setStroke(new BasicStroke(10.f));
                    circulo.setPaint(Color.blue);
                    //datos sobre el circulo
                    int radio = 40;
                    int d = radio * 2;
                    //se recorre la lista de vertices 
                    DoubleLinkedNode<PokePlace> temp = gestorPlace.listaPlaces.getHead();
                    while (temp != null) {
                        //se crea cada nodo en la pantalla con sus datos
                        circulo.drawOval(temp.getElement().getX(), temp.getElement().getY(), d, d);
                        circulo.drawString(temp.getElement().getId(), temp.getElement().getX() + 30, temp.getElement().getY() + 40);
                        circulo.drawString(temp.getElement().getTipo(), temp.getElement().getX() - 8, temp.getElement().getY() + 50);
                        //dibuja trazo
                        System.out.println(gestorPlace.getControlador().getAristas().size());
                        if (!gestorPlace.getControlador().getAristas().isEmpty()) {
                            for (int i = 0; i < gestorPlace.getControlador().getAristas().size(); i++) {
                                if (gestorPlace.getControlador().getAristas().get(i).getPuntoLlegada().equals(temp.getElement().getId()) && gestorPlace.getControlador().getAristas().get(i).getPuntoLlegada().equals(temp.getNext().getElement().getId())) {
                                    //circulo.drawLine(temp.getElement().getX(), temp.getNext().getElement().getX(), temp.getElement().getX(), temp.getElement().getX());                                 
                                }
                            }
                        }
                        temp = temp.getNext();
                    }
                }
            };
            // set background 
            c.setBackground(Color.black);

            add(c);
            setSize(1300, 700);
            show();
        }
    }
}
